import { warn } from "console";

// Expanded popular tech companies for autocomplete
export const POPULAR_COMPANIES = [
  // FAANG / Big Tech
  "Google",
  "Meta (Facebook)",
  "Amazon",
  "Netflix",
  "Apple",
  "Microsoft",
  "LinkedIn",
  "Uber",
  "Airbnb",
  "Twitter (X)",
  "Tesla",
  "OpenAI",
  "Alphabet",
  "ByteDance",
  "Snap Inc",
  "Dropbox",
  "Atlassian",
  "Zoom",
  "Pinterest",
  "Reddit",

  // Indian Tech Giants & IT Services
  "Tata Consultancy Services (TCS)",
  "Infosys",
  "Wipro",
  "HCL Technologies",
  "Tech Mahindra",
  "Cognizant",
  "Capgemini",
  "Accenture",
  "LTI Mindtree",
  "Mphasis",
  "Persistent Systems",
  "Birlasoft",
  "Zensar",
  "Coforge",
  "Cyient",

  // Indian Startups & Unicorns
  "Zomato",
  "Swiggy",
  "Paytm",
  "PhonePe",
  "CRED",
  "Razorpay",
  "Flipkart",
  "Ola",
  "Zerodha",
  "Dream11",
  "Meesho",
  "Groww",
  "Upstox",
  "Udaan",
  "Delhivery",
  "Nykaa",
  "Byju's",
  "Unacademy",
  "PhysicsWallah",
  "Ather Energy",
  "Zepto",
  "Porter",
  "InMobi",
  "ShareChat",
  "Myntra",
  "BookMyShow",
  "BharatPe",

  // Global Tech & SaaS
  "Oracle",
  "SAP",
  "IBM",
  "Adobe",
  "Salesforce",
  "Intel",
  "NVIDIA",
  "AMD",
  "Qualcomm",
  "Cisco",
  "Broadcom",
  "VMware",
  "ServiceNow",
  "Workday",
  "Snowflake",
  "Palantir",
  "Twilio",
  "Datadog",
  "Cloudflare",
  "Elastic",
  "GitHub",
  "GitLab",

  // Consulting & Professional Services
  "Deloitte",
  "PwC",
  "EY",
  "KPMG",
  "McKinsey & Company",
  "Boston Consulting Group (BCG)",
  "Bain & Company",
  "Accenture Strategy",
  "ZS Associates",
  "Alvarez & Marsal",

  // E-commerce & Fintech
  "Shopify",
  "Stripe",
  "PayPal",
  "Visa",
  "Mastercard",
  "Block (Square)",
  "Coinbase",
  "Robinhood",
  "Wise",
  "Revolut",
  "Klarna",
  "Plaid",
  "RazorpayX",
  "PayU",
  "Cashfree",
  "BillDesk",

  // Gaming, Media & Hardware
  "Sony",
  "Samsung",
  "LG",
  "Xiaomi",
  "OnePlus",
  "Nintendo",
  "Electronic Arts (EA)",
  "Ubisoft",
  "Epic Games",
  "Unity Technologies",
  "AMD Gaming",
  "Riot Games",

  // Others / Generic
  "Government of India",
  "Public Sector Unit (PSU)",
  "Non-Profit Organization (NGO)",
  "Self-Employed",
  "Freelancer",
  "Startup Founder",
  "Student",
  "Unemployed",
].sort();

// Expanded popular job roles for autocomplete
export const POPULAR_ROLES = [
  // Core Software Engineering
  "Software Engineer",
  "Associate Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Distinguished Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Platform Engineer",
  "Build & Release Engineer",

  // Mobile & Web
  "Android Developer",
  "iOS Developer",
  "React Developer",
  "Next.js Developer",
  "Flutter Developer",
  "React Native Developer",
  "Web Developer",

  // DevOps, Cloud & Infra
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Cloud Engineer",
  "Cloud Architect",
  "Infrastructure Engineer",
  "Platform Reliability Engineer",
  "Kubernetes Engineer",
  "Linux Administrator",

  // Security
  "Security Engineer",
  "Application Security Engineer",
  "Cloud Security Engineer",
  "SOC Analyst",
  "Cybersecurity Analyst",
  "Ethical Hacker",
  "Pentester",

  // Data & AI
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "Machine Learning Engineer",
  "AI Engineer",
  "Research Scientist",
  "Applied Scientist",
  "MLOps Engineer",
  "Business Intelligence Analyst",

  // Product & Management
  "Product Manager",
  "Associate Product Manager",
  "Senior Product Manager",
  "Technical Product Manager",
  "Program Manager",
  "Project Manager",
  "Scrum Master",
  "Delivery Manager",

  // Leadership
  "Technical Lead",
  "Team Lead",
  "Engineering Manager",
  "Senior Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "CTO",

  // Design & UX
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "UX Researcher",
  "Interaction Designer",
  "Design Lead",

  // Quality & Testing
  "QA Engineer",
  "Manual Tester",
  "Automation Engineer",
  "Performance Tester",
  "SDET",
  "QA Lead",
  "Test Architect",

  // Architecture
  "Solution Architect",
  "Software Architect",
  "Enterprise Architect",
  "Cloud Architect",
  "Data Architect",
  "Security Architect",

  // IT & Support
  "System Administrator",
  "Network Engineer",
  "IT Support Engineer",
  "Helpdesk Engineer",

  // Business & Consulting
  "Consultant",
  "Business Analyst",
  "Systems Analyst",
  "Management Consultant",
  "Strategy Analyst",

  // Emerging Tech
  "Blockchain Developer",
  "Web3 Developer",
  "AR/VR Engineer",
  "Game Developer",
  "Robotics Engineer",
  "IoT Engineer",

  // Early Career & Others
  "Intern",
  "Graduate Trainee",
  "Apprentice",
  "Research Intern",
  "Teaching Assistant",
  "Founder",
  "Co-Founder",
  "Entrepreneur",
  "Freelancer",
  "Contractor",
  "Student",
].sort();
// Popular skills for autocomplete (~110 skills)
export const POPULAR_SKILLS = [
  // Programming Languages
  "C",
  "C++",
  "C#",
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "Ruby",
  "PHP",
  "R",
  "MATLAB",
  "Dart",
  "Scala",
  "Perl",
  "Objective-C",
  "Assembly",

  // Web Development
  "HTML",
  "CSS",
  "Sass",
  "Tailwind CSS",
  "Bootstrap",
  "React",
  "Next.js",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Redux",
  "Zustand",
  "jQuery",
  "Node.js",
  "Express.js",
  "NestJS",
  "REST APIs",
  "GraphQL",
  "WebSockets",
  "Vite",
  "Webpack",
  "Babel",

  // Mobile Development
  "Android Development",
  "iOS Development",
  "Flutter",
  "React Native",
  "Jetpack Compose",

  // Backend & Frameworks
  "Spring",
  "Spring Boot",
  "Hibernate",
  ".NET",
  "ASP.NET",
  "Django",
  "Flask",
  "FastAPI",
  "Ruby on Rails",
  "Laravel",

  // Databases & Storage
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Oracle DB",
  "SQL Server",
  "MongoDB",
  "Redis",
  "Cassandra",
  "DynamoDB",
  "Firebase",
  "Elasticsearch",

  // Data & AI
  "Data Structures & Algorithms",
  "Data Analysis",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "scikit-learn",
  "Pandas",
  "NumPy",
  "Apache Spark",
  "Hadoop",
  "Kafka",

  // DevOps & Cloud
  "AWS",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "CI/CD",
  "Jenkins",
  "GitHub Actions",
  "GitLab CI",
  "Linux",
  "Bash",
  "Shell Scripting",
  "Nginx",
  "Apache",

  // Testing & QA
  "Unit Testing",
  "Integration Testing",
  "JUnit",
  "Mockito",
  "Selenium",
  "Cypress",
  "Playwright",
  "Jest",
  "Mocha",
  "Postman",
  "Load Testing",

  // Security
  "Cybersecurity",
  "Penetration Testing",
  "OWASP",
  "OAuth",
  "JWT",
  "Application Security",

  // System Design & Architecture
  "System Design",
  "Low-Level Design (LLD)",
  "High-Level Design (HLD)",
  "Microservices Architecture",
  "Monolith Architecture",
  "Event-Driven Architecture",

  // Version Control & Collaboration
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",

  // Product, Analytics & Tools
  "Agile",
  "Scrum",
  "JIRA",
  "Confluence",
  "Figma",
  "Adobe XD",
  "Canva",
  "Google Analytics",
  "Mixpanel",

  // Blockchain & Web3
  "Blockchain",
  "Ethereum",
  "Solidity",
  "Smart Contracts",
  "Web3.js",

  // Soft & Professional Skills (Important for profiles)
  "Problem Solving",
  "Communication",
  "Teamwork",
  "Leadership",
  "Time Management",
  "Critical Thinking",
  "Public Speaking",
  "Mentorship",

  // Others / Generic
  "API Development",
  "Payment Gateways",
  "Search Engine Optimization (SEO)",
  "Web Performance Optimization",
].sort();
